# Generated by Django 4.0.3 on 2022-04-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_curso_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='lastname',
            new_name='apellido',
        ),
    ]
